apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: $NAMESPACE
spec:
  selector:
    app: $APP_NAME
    role: Frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-deployment
  namespace: $NAMESPACE
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: $APP_NAME
        role: Frontend
    spec:
      containers:
        - name: $APP_NAME
          imagePullPolicy: Always
          image: $IMAGE_NAME
          ports:
            - containerPort: 80
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $INGRESS_NAME
  namespace: $NAMESPACE
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: $HOSTNAME
    http:
      paths:
      - path: /
        backend:
          serviceName: web-service
          servicePort: 80
